# Insert your secrets here 
# and rename the file to kustomization.yaml
secretGenerator:
- name: lvalert-secrets
  namespace: lvalert
  literals:
  - admin-password=<changeme>
  - encryption-key=<changeme>
  - db-password=<changeme>
  - db-root-password=<changeme>
  - lvalert-password=<changeme>
- name: mysql-initdb-config
  namespace: lvalert
  literals:
  - initdb.sql=GRANT ALL PRIVILEGES ON *.* TO ''@'127.0.0.1' IDENTIFIED BY '<changeme(should be db-password)>';
               FLUSH PRIVILEGES;
generatorOptions:
  disableNameSuffixHash: true
