apiVersion: v1
kind: PersistentVolume
metadata:
  name: lvalert-mysql-pv
  namespace: lvalert
spec:
  storageClassName: "cinder"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: lvalert 
    name: lvalert-mysql-pvc
  hostPath:
    path: "/mnt/mysql-lvalert"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lvalert-mysql-pvc
  namespace: lvalert
spec:
  storageClassName: "cinder"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
