#!/bin/bash

# Get lvalert login params from env
echo "machine ${LVALERT_SERVER} login ${LVALERT_USER} password ${LVALERT_PASSWORD}" > /root/.netrc
chmod 600 /root/.netrc

eval "echo \"$(cat add_nodes.template)\"" > /root/add_nodes.py
#exec "$@"
python /root/add_nodes.py
